### ISSUE TITLE
Odd-looking scroll bars on tabbed widget

### ISSUE THREAD

**Issue by jackwilsdon** [NiceDash/Vibe#1]
![Tab Widget](https://user-images.githubusercontent.com/1843197/54745597-cb1da600-4bc1-11e9-91dd-fac678bfa41c.png)

Firefox 66.0 on Windows 10

**Comment by PiotrSzponar** [comment]
Unnecessary `margin-bottom` at `.nav-tabs .nav-item`
https://github.com/NiceDash/Vibe/pull/2

**Comment by julians300** [comment]
I am still seeing a horizontal scroll bar on windows. The idea was to make the tabs scrollable for a better mobile responsive experience but it's coming at the expense of the design. Also it's not working properly.

I am removing `overflow-x: scroll;` from the `.nav-tabs` class until a better solution for responsive tabs is created.

**Comment by julians300** [comment]
https://github.com/NiceDash/Vibe/pull/5 Should fix this. 🙂
